[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Henrik Berg <henrik.berg.3@volvocars.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
